apiVersion: v2
name: thanos
description: Helm chart for Thanos.
type: application
version: 1.0.0
appVersion: 0.30.2
keywords:
  - kubernetes
  - thanos
  - monitoring
  - alerting
  - metrics
home: https://thanos.io/
icon: https://cncf-branding.netlify.app/img/projects/thanos/icon/color/thanos-icon-color.png
sources:
  - https://github.com/thanos-io/thanos
  - https://github.com/thanos-io/kube-thanos
  - https://github.com/k8sonlab/publiccharts
maintainers:
- e-mail: v.aretakis@gmail.com
  name: Vassilis Aretakis
  url: https://github.com/varet80
