{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels: 
    {{- include "zwave-js-ui.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "zwave-js-ui.fullname" . }}
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.interval }}
    port: {{ .Values.ports.ui.name }}
  {{- with .Values.serviceMonitor.namespaceSelector }}
  namespaceSelector:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zwave-js-ui.selectorLabels" . | nindent 6 }}
{{- end }} 
