name: Release Charts

on:
  pull_request:
    branches:
      - main

jobs:
   check_release:
    runs-on: ubuntu-latest
    steps:

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          changed=""
          reqsubstr="charts/"
          for file in ${{ steps.files.outputs.all }}; do
            if [ -z "${file##*$reqsubstr*}" ] ;then
              chartName=$(echo $file | awk -F "/" '{print $2}')
              echo $chartName
              if [ ! $changed =~ $chartName ]; then
                changed=$changed $chartName
              fi
            fi
          done
          echo $changed