name: Release Charts

on:
  pull_request:
    branches:
      - main

jobs:
   check_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: prepate yq
        run: |
          curl https://github.com/mikefarah/yq/releases/download/`curl --silent "https://api.github.com/repos/mikefarah/yq/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'`/yq_linux_amd64 -L -o yq
          chmod 755 yq
      - name: bumper
        run: |
          changed=""
          reqsubstr="charts/"
          for file in ${{ steps.files.outputs.all }}; do
            if [ -z "${file##*$reqsubstr*}" ] ;
            then
              chartName=$(echo $file | awk -F "/" '{print $2}')
              if [[ ! $changed =~ $chartName ]];
              then
                changed="$changed $chartName"
              fi
            fi
          done
          ls -l
          for chart in $changed; do
            echo chart is: "${chart}-$(yq '.version' charts/${chart}/Chart.yaml)"
            git rev-parse "${chart}-$(yq '.version' charts/${chart}/Chart.yaml)"
          done