name: Compatibility

on:
  pull_request:
    branches:
      - main

jobs:
  PlutoChecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Add repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Add dependencies
        run: |
          set -E
          for chart in $(ls -b charts/); do
            helm dependency update charts/${chart}
          done
      - name: Check compatibility
        run: |
          set -E
          for chart in $(ls -b charts/); do
            helm template charts/${chart} | pluto detect --target-versions k8s=v1.16.0 -
          done
